name: Bicep Lint

on:
  pull_request:
    paths:
      - 'AzureArchitecture/**/*.bicep'
      - 'AzureArchitecture/bicepconfig.json'
  workflow_dispatch: {}

jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bicep CLI
        run: |
          curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
          chmod +x ./bicep
          sudo mv ./bicep /usr/local/bin/bicep
          bicep --version

      - name: Build all Bicep files (fail on warnings)
        working-directory: AzureArchitecture
        run: |
          set -e
          failed=0
          for f in $(ls *.bicep); do
            echo "Building $f"
            # -w Treats warnings as errors
            if ! bicep build "$f" --no-restore -w; then
              failed=1
            fi
          done
          if [ "$failed" -ne 0 ]; then
            echo "Bicep build failed due to warnings or errors"
            exit 1
          fi
