name: Deploy Management Portal (Simple)

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [ main, master ]
    paths:
      - 'management-portal/**'
  workflow_dispatch:

env:
  AZURE_SUBSCRIPTION_ID: 480cb033-9a92-4912-9d30-c6b7bf795a87
  RESOURCE_GROUP_NAME: rg-stamps-mgmt-prod
  LOCATION: westus2

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: 480cb033-9a92-4912-9d30-c6b7bf795a87

    - name: Build .NET Application
      run: |
        cd management-portal/src/Portal
        dotnet build --configuration Release

    - name: List Azure Container Apps
      run: |
        echo "Listing container apps to verify authentication..."
        az containerapp list --resource-group ${{ env.RESOURCE_GROUP_NAME }} --output table || echo "No container apps found or authentication failed"
        
    - name: Show Current Portal
      run: |
        echo "Current portal should be accessible at:"
        echo "https://ca-stamps-portal.wittywave-3d4ef36b.westus2.azurecontainerapps.io"
        echo ""
        echo "This is a simple deployment test to verify authentication works."
        echo "Once authentication is working, we can enable the full deployment."
