name: Docs link check (Manual Only)

on:
  workflow_dispatch: {}

jobs:
  link-check:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate relative links (including images)
        shell: pwsh
        run: ./scripts/verify-doc-links.ps1 -IncludeImages
