name: Docs Link Check (Manual Only)

on:
  workflow_dispatch: {}

concurrency:
  group: link-check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lychee:
    name: Check links with lychee
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run lychee link checker
        uses: lycheeverse/lychee-action@v2
        with:
          # Respect config file settings; output summary and fail on broken links
          args: >-
            --config lychee.toml
            --no-progress
            --max-redirects 10
            --timeout 20
            --retry-wait-time 2
            --max-retries 2
            --format detailed
            --exclude-mail
            **/*.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload lychee report (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lychee-report
          path: |
            lychee-out.md
            lychee-out.txt
            lychee-cache*
