name: Markdown Lint

on:
  pull_request:
    branches: [ master ]
    paths:
      - '**/*.md'
      - '.github/workflows/markdownlint.yml'
      - '.markdownlint.jsonc'
  push:
    branches: [ master ]
    paths:
      - '.markdownlint.jsonc'
  workflow_dispatch: {}

concurrency:
  group: mdlint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install markdownlint-cli2
        run: |
          npm install -g markdownlint-cli2

      - name: Run markdownlint
        run: |
          markdownlint-cli2 "**/*.md" "!**/bin/**" "!**/obj/**" || exit 1
